name: Push-to-EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-20.04.5
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Deploy to Server 1
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SOURCE: "."
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}
        SCRIPT_BEFORE: |
          sudo ps -ax | grep poetry | grep -v grep | awk '{print $1}' | xargs kill
        SCRIPT_AFTER: |
          cd ${{ secrets.TARGET_DIR }}
          export ADE_PASSWORD=${{ secrets.ADE_PASSWORD }}
          export ADE_USERNAME=${{ secrets.ADE_USERNAME }}
          export DEVELOPER_CHAT_ID=${{ secrets.DEVELOPER_CHAT_ID }}
          export TOKEN_BOT_TELEGRAM=${{ secrets.TOKEN_BOT_TELEGRAM }}
          nohup poetry run run-app
